### ISSUE TITLE
Strings are highlighted incorrectly with monokia on chrome tamper monkey

### ISSUE THREAD

**Issue by michaelmesser** [StylishThemes/GitHub-Dark-Script#14]
![image](https://cloud.githubusercontent.com/assets/16529951/15504049/1bc70fc4-218b-11e6-809f-fbb8a8584011.png)
The quotation marks are highlighted correct but the contents of the string is not.

**Comment by Mottie** [comment]
Thanks for reporting this, it's all fixed now.

**Comment by Mottie** [comment]
To update this, you'll need to switch to a different syntax highlighting theme, then do a "force update". Then choose Monokai again, because the script caches the chosen theme file.

**Comment by michaelmesser** [comment]
Wow. That was fast.

**Comment by Mottie** [comment]
:grin:

**Comment by michaelmesser** [comment]
Still not working. I changed the syntax theme. Hit "Force Update Style" and changed back to Monokia. Same highlighting. Somehow it must still be cached.

**Comment by Mottie** [comment]
Try again... sometimes the `raw.githubusercontent.com` file doesn't update immediately; and that is where the script pulls the style from.

**Comment by michaelmesser** [comment]
Still not working.

**Comment by silverwind** [comment]
Something about that force update isn't working for me either, checking it out.

**Comment by Mottie** [comment]
Hey @2426021684! Add `?debug` to the URL and look in the console after reloading the page... it should tell you which theme is being loaded; click the link and search for ".type-css" - if it's there, it's loading the newest Monokai file.

**Comment by michaelmesser** [comment]
".type-css" is there. In theme css and in processed css.

**Comment by Mottie** [comment]
You're not also using the Stylish userstyle are you? Stylish overrides the script... the userstyle was also updated.

**Comment by silverwind** [comment]
I think I found the issue, gimme a sec :)

**Comment by silverwind** [comment]
Hmm, something is still wrong (e.g. theme not applying), sec.

**Comment by michaelmesser** [comment]
I am not using the Stylish usersheet.

**Comment by silverwind** [comment]
Hopefully fixed the theme update issue on master. Monokai strings still looking weird thought:

![](https://cloud.githubusercontent.com/assets/115237/15515049/6dfb8584-21ec-11e6-9088-1860e30e8f8d.png)

This is what Monokai is supposed to look like: 
![](https://coderwall-assets-0.s3.amazonaws.com/uploads/picture/file/3686/javascript.png)

Guess we need to update the theme now to match it more closely.

**Comment by Mottie** [comment]
Hmm, I only updated Monokai string colors [for css](https://github.com/StylishThemes/GitHub-Dark/blob/master/themes/src/monokai.css#L103):

I guess I should just change that to the overall `.pl-s` definition.

**Comment by Mottie** [comment]
Ok, try it now... everything was updated.

**Comment by silverwind** [comment]
Also, install through https://github.com/StylishThemes/GitHub-Dark-Script/raw/master/github-dark-script.user.js

**Comment by michaelmesser** [comment]
Monokia works but many other themes have the same issue

**Comment by michaelmesser** [comment]
Also I don't ever see the red/pink color in monokia

**Comment by Mottie** [comment]
Like what themes? The GitHub syntax highlighter isn't as nice as pygments, so a lot of the themes had to be manually converted - it wasn't a perfect conversion.

**Comment by michaelmesser** [comment]
Cobalt:
<img width="804" alt="untitled 3" src="https://cloud.githubusercontent.com/assets/16529951/15515962/84472f42-21be-11e6-85cf-e1ce68c84fcf.png">

**Comment by michaelmesser** [comment]
Monokia now has the red/pink color

**Comment by silverwind** [comment]
Did a few more updates to Monokai so it closer matches the screenshot above. Theme work is usually a quite time intensive task, so I guess if you really love a theme, you can submit a pull request to perfect it.

![](https://cloud.githubusercontent.com/assets/115237/15516311/7cca365e-21f2-11e6-8a94-5968bc7f3c32.png)

The quote being a different color than the string is a bug in my eyes though, we should match the color of the involved classes.

**Comment by Mottie** [comment]
It would really help out if you would share specific changes that need to be made. I get really frustrated trying to match colors when GitHub's syntax class names are limited.

**Comment by silverwind** [comment]
Okay, cobalt strings should be fixed too:

![](https://cloud.githubusercontent.com/assets/115237/15516975/943b6418-21f5-11e6-89e4-71521d255867.png)

If you have more theme issues, please bring them up at https://github.com/StylishThemes/GitHub-Dark/issues, ideally with a screenshot what's wrong and a screenshot on how it shall look like.

**Comment by michaelmesser** [comment]
Looks fantastic now

**Comment by Mottie** [comment]
@silverwind You :metal:! Let me know when you're done tweaking themes... I'll push an update to userstyles.

**Comment by silverwind** [comment]
Go ahead, not in the mood for more theme work right now, it's so inconvenient to test. :stuck_out_tongue:

**Comment by Mottie** [comment]
That's why I made this page: https://github.com/StylishThemes/GitHub-Dark/wiki/Highlighting
