### ISSUE TITLE
White area (element change) issue page

### ISSUE THREAD

**Issue by CollinChaffin** [StylishThemes/GitHub-Dark-Script#55]
As shown here as of today:

![snag_12-6-2018_12-38-38](https://user-images.githubusercontent.com/9301483/49604781-bad11a80-f986-11e8-937e-85c0c765db4d.png)

**Comment by xt0rted** [comment]
This was fixed in https://github.com/StylishThemes/GitHub-Dark/commit/acc76270b620027e7e4adeb98421305b00b1278b earlier today. Forcing an update should fix the issue for you.

**Comment by CollinChaffin** [comment]
Hi when does the userscript get rebuilt?  It's still on 12/1 and isn't reflecting the update as of yet.  Thanks!

EDIT:  @xt0rted  I believe GF is auto-pulling from this repo which is the one that still shows 12/1 I was going to ask what conversion process/util you use to convert the usercss to the userscript for this repo?

EDIT2:  Doh!  I see now that the userscript is just dynamically pulling the CSS (and forcing through it did in fact reflect the change) so it's all good I thought back in the older versions the CSS was actually embedded.  Thx!

**Comment by Bluscream** [comment]
I updated the style within stylus and even tried reinstalling it without success :(

**Comment by Mottie** [comment]
Try updating now, I just released a new minor version (of GitHub Dark, not the script). Stylus' usercss won't update unless the version is different.

**Comment by Mottie** [comment]
> when does the userscript get rebuilt

We only rebuild this userscript if there is something broken, or a new option is added. And you're right, it pulls the style directly from the GitHub-Dark repository. It updates every 24 hours (while the userscript is running) starting from installation, or the last forced update.
