### ISSUE TITLE
White Bar on GHE Pages

### ISSUE THREAD

**Issue by szarroug3** [StylishThemes/GitHub-Dark-Script#76]
* **Browser**: Firefox
* **Operating System**: Arch Linux
* **Link to page with the issue**: Github Enterprise Page
* **Screenshot**: 
![ghe-bug](https://user-images.githubusercontent.com/8463185/74379109-d155db80-4dac-11ea-9c16-f22f0671dc77.png)

On Github Enterprise, it seems the bar the background is not being applied to the top bar where you can click "Code", "Issues", "Pull Requests", etc causing the background to be white rather than match the rest of the page.

**Comment by silverwind** [comment]
This is probably https://github.com/StylishThemes/GitHub-Dark/issues/1057. Try force-updating.

**Comment by szarroug3** [comment]
I did, nothing happened but you're right. It's the same issue. I can follow that one if you want to close this one.

**Comment by xt0rted** [comment]
A portion of this style is auto generated from the css on github.com, so sometimes when UI changes are made and we regenerate the style it works fine on github.com but breaks on GHE installs. You'll probably need to install a copy of this style from a few days ago before this change was fixed and use that until your GHE instance is updated to a newer version.

**Comment by szarroug3** [comment]
Ahhh okay cool I'll try that in the morning. Thanks!

**Comment by the-j0k3r** [comment]
GitHub Dark script does not account for extra moz-document sections. Needs fixing. See info on https://github.com/StylishThemes/GitHub-Dark-Script/issues/75

**Comment by szarroug3** [comment]
@xt0rted I went back to older versions (going back as far as june 2019) and it's still happening
@the-j0k3r I switched to stylus and github dark and it's still happening

**Comment by silverwind** [comment]
Find the CSS selector of the rule that adds the background and post the full rule here. We generally can't really support GHE by other means unfortunately.

**Comment by szarroug3** [comment]
I did some messing around in the css for stylus. Adding the following worked for me:
`.repohead.experiment-repo-nav {
    background-color: transparent !important;
}`

**Comment by szarroug3** [comment]
it seems like the comment bar is also doing the same thing so I'll do some more digging and see if i can figure out the selector for that too :)

**Comment by silverwind** [comment]
Can you post the original rule out of GHE CSS?

**Comment by szarroug3** [comment]
To fix the comment bar:

`.new-discussion-timeline .previewable-comment-form .comment-form-head.tabnav { background-color: transparent !important}`


How do I get the original rule out of the CSS? Sorry I'm not really a web dev.

**Comment by szarroug3** [comment]
Is this what you're looking for?

`.repohead.experiment-repo-nav {
	background-color: #fafbfc;
	padding-bottom: 0;
}`

**Comment by silverwind** [comment]
Yes, added that in https://github.com/StylishThemes/GitHub-Dark/commit/133104f7f7e7086e234bd86828f886e685dd4ac5. Try force-updating the style.

**Comment by szarroug3** [comment]
Wonderful! Thanks for fixing that. The white bar on the comments box is still there:
![2020-02-18_15-10](https://user-images.githubusercontent.com/8463185/74778289-df01da00-5260-11ea-8b82-e0f9848a7131.png)

I was able to fix that one using the following:
`  .new-discussion-timeline .previewable-comment-form .comment-form-head.tabnav {
    background-color: transparent !important;
  }`


This is the original rule:
`.new-discussion-timeline .previewable-comment-form .comment-form-head.tabnav {
	background: #f6f8fa;
	border-radius: 3px 3px 0 0;
	padding: 6px 10px 0;
}`

**Comment by xt0rted** [comment]
That's the same issue as https://github.com/StylishThemes/GitHub-Dark/issues/989. There's some information in there from someone else who was fixing it for their GHE instance.

**Comment by silverwind** [comment]
@szarroug3 can you show the CSS rule affecting the triangle on the left? It should be `::after` element on the `.timeline-comment` element. The github.com rule is

```css
.timeline-comment--caret::after {
    border-right-color: #f6f8fa;
}

**Comment by silverwind** [comment]
Comment form should be done in https://github.com/StylishThemes/GitHub-Dark/commit/9b8cb8225227454bb02333dcb1ecac731dfab93e minus the triangle.

**Comment by szarroug3** [comment]
@silverwind 
```
.timeline-comment-wrapper .timeline-comment.current-user::after {
	border-right-color: #f1f8ff;
	border-width: 7px;
	margin-left: 2px;
	margin-top: 1px;
}
```

I think you might also need this:
```
.timeline-comment-wrapper > .timeline-comment::before, .timeline-new-comment .timeline-comment::before {
	border-right-color: #d1d5da;
	border-width: 8px;
}
```

**Comment by silverwind** [comment]
try force update again

**Comment by szarroug3** [comment]
that doesn't seem to have worked:
![comment-box](https://user-images.githubusercontent.com/8463185/74872500-eab5d500-5322-11ea-86c3-28f128f436dc.png)
![comment-box2](https://user-images.githubusercontent.com/8463185/74872507-ed182f00-5322-11ea-9a5a-cbb5670100d3.png)

Looks like it made it disappear on github.com altogether:
![comment-box3](https://user-images.githubusercontent.com/8463185/74872600-2355ae80-5323-11ea-9fcd-c5b90fc05add.png)

**Comment by szarroug3** [comment]
Sorry! I might've given you the wrong rule. Here's the correct one:
```
.timeline-comment-wrapper > .timeline-comment::after, .timeline-new-comment .timeline-comment::after {
	border-right-color: #f6f8fa;
	border-width: 7px;
	margin-left: 2px;
	margin-top: 1px;
}
```

**Comment by silverwind** [comment]
Try again. By the way, can you post the `<html>` and `<body>` tags of your GHE instance? Similar to this one:

<img width="572" src="https://user-images.githubusercontent.com/115237/74874127-b6610980-5360-11ea-8f52-d16d38068c12.png">

Askinng because I'd like to scope the GHE selectors so they cannot affect github.com.

**Comment by szarroug3** [comment]
Hm, still no luck, it looks the same. Here are the tags you asked for:
![html-body](https://user-images.githubusercontent.com/8463185/74882814-64ef5500-5335-11ea-9d3d-6ed937852576.png)

**Comment by szarroug3** [comment]
These lines fixed the comment box and the current user box for me:

```
  /* current user */
  .timeline-comment-wrapper .timeline-comment.current-user::before {
    border-right-color: #246;
  }
  .timeline-comment-wrapper .timeline-comment.current-user::after {
    border-right-color: #182030;
  }
  
  /* comment box */
  .timeline-new-comment .timeline-comment::before {
	  border-right-color: #404040;
  }
  .timeline-new-comment .timeline-comment::after {
    border-right-color: #202020;
  }
```

**Comment by silverwind** [comment]
Scoped the selectors and copied yours in, try again.

**Comment by szarroug3** [comment]
Looks like that fixed the user comment box and the make a comment box but not the other people commented box, i'll look for that one right now

**Comment by szarroug3** [comment]
Oh duh, ignore that. Other user's comments don't have a triangle. Seems like everything is fixed now. Thanks!

**Comment by szarroug3** [comment]
Ignore that, it looks like other people's comment's don't have a triangle next to them on GHE for some reason. Thanks for fixing everything! :smile:

**Comment by silverwind** [comment]
🎉
